### PR TITLE
add swift sample app + Card editing form

### PR DESCRIPTION
**Pull request by romansavrulin**
Tiny swift demo app, to make life a little simpler.

Без названия

### CODE REVIEW

**Comment by romansavrulin** [comment]
ping @slavabuv. Is this PR interesting for you?

**Comment by illabo** [comment]
Hey there! Mind I ask have you tested ApplePay with the real terminal id and PKContact and CNPostalAddress present? I'm getting 9999 error code from Tinkoff and looking for help. :)

**Comment by romansavrulin** [comment]
Hello! Haven’t tested it with contact and address fields, but without them SDK works almost fine. The only thing we have is runtime exception somewhere in card editing form, when network connetion is not available. We’ve implemented a workaround for this, but will look into the main reason a bit later and make a PR. I guess this could be somehow related to your issue (maybe responses from server has changed or so)

**Comment by illabo** [comment]
Thx for reply! Just ceased to use contact and delivery info and it's fine now. :)

**Pull request closed without merging**
